services:
  - type: web
    name: fastapi-sacco
    runtime: python
    plan: free  # or starter, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cheontec
          property: connectionString

databases:
  - name: cheontec
    databaseName: cheontec
    user: root